server:
  port: 8080

spring:
  application:
  name: chat_online
  datasource:
    url: jdbc:mysql://localhost:3306/chat_online_db?createDatabaseIfNotExist=true
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
